#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
    path: /logout
    methods: GET

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /admin
    type: annotation
