easy_admin:
  design:
    menu:
      - label: 'Home'
        icon: 'home'
        permission: [ROLE_ADMIN]
        children:
          - { label: 'Usuario', entity: 'Usuario', icon: 'user' }
          - { label: 'Gallery', entity: 'Gallery', icon: 'picture-o' }
